### ISSUE TITLE
CRAN check warning about `_exit`, `abort` and `exit`

### ISSUE THREAD

**Issue by yutannihilation** [yutannihilation/savvy#355]
https://cran.r-project.org/web/checks/check_results_string2path.html

```
  File ‘string2path/libs/string2path.so’:
    Found ‘_exit’, possibly from ‘_exit’ (C)
      Object: ‘rust/target/release/libstring2path.a’
    Found ‘abort’, possibly from ‘abort’ (C)
      Object: ‘rust/target/release/libstring2path.a’
    Found ‘exit’, possibly from ‘exit’ (C)
      Object: ‘rust/target/release/libstring2path.a’
  
  Compiled code should not call entry points which might terminate R nor
  write to stdout/stderr instead of to the console, nor use Fortran I/O
  nor system RNGs nor [v]sprintf.
  
  See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual
```

**Comment by yutannihilation** [comment]
https://github.com/r-devel/r-svn/blob/b74106735de14725c7e5ebe41fce29da086a1781/src/library/tools/R/check.R#L4030-L4034

**Comment by yutannihilation** [comment]
- [Add `_R_CHECK_COMPILED_CODE_USE_OBJECTS_SYMBOL_TABLES_` env var to allow experimenting with PR#18789.](https://github.com/r-devel/r-svn/commit/49265f4d821ca83e334d2cd14f62686df72ca7fc)
- [Include symbols from static libraries used in `PKG_LIBS` in symbols.rds (PR#18789).](https://github.com/r-devel/r-svn/commit/38b2a4124ea4b7b838827ed3df4af40a4ea0ce70)

**Comment by yutannihilation** [comment]
https://bugs.r-project.org/show_bug.cgi?id=18789#c2

**Comment by yutannihilation** [comment]
After some thinking, I'm in the mood this cannot be fixed. Since Rust is not C, it cannot unwind to longjmp. So, the only possible strategy is just to abort and crash the R session. Are there any way to crash R gracefully...?

**Comment by yutannihilation** [comment]
Maybe I'm just confused. Let's rethink after enough sleep.

**Comment by yutannihilation** [comment]
hellorust fixed this so quickly. It seems this was just that the intermediate static lib was not cleaned up.

https://github.com/r-rust/hellorust/commit/9a3ab01fd7ce6b3e5ee24d5af5e8ca3b28abd71f

**Comment by yutannihilation** [comment]
It seems this didn't work on the CRAN machine. But why...?

https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/string2path-00check.html

```
rm -Rf /data/gannet/ripley/R/packages/tests-clang/string2path/src/.cargo ./rust/target//release/build
```

**Comment by eitsupi** [comment]
Since the problem is fixed in hellorust, could it be due to the way relative paths are specified?

I believe it is recommended to use `$(CURDIR)` in the Makefile instead of `.`.

**Comment by yutannihilation** [comment]
Ah, sorry, that line was unrelated. I think I now understand. The difference between hellorust is that I didn't add `$(SHLIB)` to the dependencies. This won't be a problem when the make is executed in serial, but `clean_intermediate` can be executed before `$(SHLIB)`

string2path:

``` makefile
all: $(SHLIB) clean_intermediate

...

clean_intermediate:
	rm -Rf $(STATLIB) ./rust/.cargo
```

hellorust:

```makefile
all: $(SHLIB) cleanup

...

cleanup: $(SHLIB)
	rm -Rf $(STATLIB) myrustlib/target
```

**Comment by eitsupi** [comment]
Oh, I see. I had forgotten whether Make executes dependencies in parallel or in order.

**Comment by yutannihilation** [comment]
I still don't succeed to reproduce the warning on my local or on r-hub, but that's the only possibility that I come up with...

**Comment by yutannihilation** [comment]
I'm wondering if these warnings indicate it's a bit too early to remove the static lib. Maybe I can just ignore. Maybe not. 

https://www.r-project.org/nosvn/R.check/r-devel-macos-arm64/hellorust-00check.html

`warning: (arm64) /Volumes/Builds/packages/big-sur-arm64/results/4.5/hellorust.Rcheck/00_pkg_src/hellorust/src/myrustlib/target/release/libmyrustlib.a(std-019f0f6ae6e6562b.std.5e488047b44b26af-cgu.0.rcgu.o) unable to open object file: No such file or directory`

**Comment by yutannihilation** [comment]
```
## macOS does not keep debugging symbols in binaries
## anymore so optionally we can create dSYMs. This is
## important since we will blow away .o files so there
## is no way to create it later.
```
https://github.com/r-devel/r-svn/blob/7c86ae9de4c6ab1749ae37744ae4b0dc4836dd7e/src/library/tools/R/install.R#L585-L594

**Comment by yutannihilation** [comment]
`--dsym` looks an option for debugging. For CRAN check, this is probably set because it would be easier to investigate when some problem is found. But, probably this doesn't matter to the ordinary package users.

cf. https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Debugging-on-macOS

Honestly this is beyond my understanding, but I decided to just ignore this.

**Comment by yutannihilation** [comment]
It seems https://github.com/yutannihilation/savvy/pull/359 fixes the remaining CRAN warnings.

https://cran.r-project.org/web/checks/check_results_string2path.html (at the time of writing, this still shows one warning, but I bet it will disappear)

**Comment by eitsupi** [comment]
I don't think it is necessary to have `$(SHLIB)` as a dependency on `all` because it needs to be executed in order.
Like: r-rust/hellorust#23

**Comment by eitsupi** [comment]
WRE says:

> Note that Makevars should not normally contain targets, as it is included before the default makefile and make will call the first target, intended to be all in the default makefile. If you really need to circumvent that, use a suitable (phony) target all before any actual targets in Makevars.[win]:

<https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Using-Makevars-1>

So it seems that having `all` is good.

**Comment by yutannihilation** [comment]
Oh, good to know. Thanks.

**Comment by yutannihilation** [comment]
One reason I'm not fully convinced is that, this looks really tricky. All we need to do is not only cleaning up. Maybe I need to come up with a bit more nice name...

```make
all: cleanup
```

**Comment by yutannihilation** [comment]
After thinking about this for a while, I decided not to change the current `Makevars` template. In theory, you are right in that it's unnecessary to have `$(SHLIB)`. However, being unnecessary doesn't always mean it's meaningless. I think there's nothing wrong to keep `$(SHLIB)` to make the intention clear; `all` that we want to do is to create `$(SHLIB)` and then do some `cleanup`.

```make
all: $(SHLIB) cleanup
```

That's just because I'm poor at `make`, but this is my conclusion at the moment. Thanks for the suggestion anyway!
